unit MDN110UM2;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs, 
  ExtCtrls, StdCtrls, Buttons, Grids, UltraGrid, Mask, ComCtrls, Variants;

type
  TMDN110FM2 = class(TForm)
    pc_ICU: TPageControl;
    ts_ICU1: TTabSheet;
    ts_ICU2: TTabSheet;
    sbox_Tab2: TScrollBox;
    Bevel79: TBevel;
    Label26: TLabel;
    Bevel89: TBevel;
    Label27: TLabel;
    Panel23: TPanel;
    Bevel93: TBevel;
    Label28: TLabel;
    Panel27: TPanel;
    Bevel96: TBevel;
    Bevel97: TBevel;
    RadioButton19: TRadioButton;
    RadioButton20: TRadioButton;
    Bevel110: TBevel;
    Label30: TLabel;
    Panel36: TPanel;
    Bevel111: TBevel;
    Bevel112: TBevel;
    Bevel113: TBevel;
    CheckBox45: TCheckBox;
    CheckBox46: TCheckBox;
    CheckBox47: TCheckBox;
    Edit19: TEdit;
    Bevel105: TBevel;
    Label34: TLabel;
    Edit20: TEdit;
    Bevel102: TBevel;
    Label32: TLabel;
    Edit21: TEdit;
    Bevel103: TBevel;
    Label33: TLabel;
    Edit22: TEdit;
    Bevel107: TBevel;
    Label35: TLabel;
    Bevel116: TBevel;
    Label37: TLabel;
    Panel34: TPanel;
    Edit23: TEdit;
    Panel40: TPanel;
    Panel41: TPanel;
    Bevel123: TBevel;
    Bevel127: TBevel;
    RadioButton23: TRadioButton;
    RadioButton24: TRadioButton;
    Bevel128: TBevel;
    Bevel129: TBevel;
    RadioButton25: TRadioButton;
    RadioButton26: TRadioButton;
    Bevel130: TBevel;
    Bevel131: TBevel;
    RadioButton27: TRadioButton;
    RadioButton28: TRadioButton;
    Panel42: TPanel;
    Panel43: TPanel;
    Panel130: TPanel;
    Bevel217: TBevel;
    Bevel216: TBevel;
    Label91: TLabel;
    Bevel241: TBevel;
    Label92: TLabel;
    CheckBox134: TCheckBox;
    Edit45: TEdit;
    Edit46: TEdit;
    Panel60: TPanel;
    Panel61: TPanel;
    Panel63: TPanel;
    Bevel198: TBevel;
    Bevel199: TBevel;
    Bevel200: TBevel;
    CheckBox98: TCheckBox;
    CheckBox99: TCheckBox;
    CheckBox100: TCheckBox;
    Panel65: TPanel;
    Bevel207: TBevel;
    Bevel208: TBevel;
    Bevel209: TBevel;
    Bevel210: TBevel;
    Bevel211: TBevel;
    CheckBox103: TCheckBox;
    CheckBox104: TCheckBox;
    CheckBox105: TCheckBox;
    CheckBox106: TCheckBox;
    CheckBox107: TCheckBox;
    Bevel192: TBevel;
    Bevel194: TBevel;
    CheckBox95: TCheckBox;
    CheckBox96: TCheckBox;
    Bevel195: TBevel;
    Bevel196: TBevel;
    Bevel197: TBevel;
    CheckBox97: TCheckBox;
    CheckBox101: TCheckBox;
    CheckBox102: TCheckBox;
    Bevel201: TBevel;
    CheckBox108: TCheckBox;
    Bevel48: TBevel;
    Panel11: TPanel;
    Bevel49: TBevel;
    Bevel50: TBevel;
    RadioButton9: TRadioButton;
    RadioButton10: TRadioButton;
    Panel21: TPanel;
    Bevel83: TBevel;
    Bevel84: TBevel;
    Bevel85: TBevel;
    Bevel86: TBevel;
    CheckBox32: TCheckBox;
    CheckBox33: TCheckBox;
    CheckBox34: TCheckBox;
    CheckBox35: TCheckBox;
    Bevel51: TBevel;
    Label23: TLabel;
    Panel12: TPanel;
    Panel13: TPanel;
    Bevel52: TBevel;
    Bevel53: TBevel;
    RadioButton11: TRadioButton;
    RadioButton12: TRadioButton;
    Bevel54: TBevel;
    Bevel55: TBevel;
    RadioButton15: TRadioButton;
    RadioButton16: TRadioButton;
    Bevel57: TBevel;
    Bevel58: TBevel;
    RadioButton38: TRadioButton;
    RadioButton39: TRadioButton;
    Bevel59: TBevel;
    Label62: TLabel;
    Panel14: TPanel;
    Bevel60: TBevel;
    Bevel61: TBevel;
    RadioButton17: TRadioButton;
    RadioButton18: TRadioButton;
    Bevel62: TBevel;
    Label63: TLabel;
    Panel17: TPanel;
    Bevel63: TBevel;
    Bevel64: TBevel;
    RadioButton21: TRadioButton;
    RadioButton22: TRadioButton;
    Bevel66: TBevel;
    Label64: TLabel;
    Panel18: TPanel;
    Panel19: TPanel;
    Bevel82: TBevel;
    Bevel87: TBevel;
    RadioButton42: TRadioButton;
    RadioButton43: TRadioButton;
    Bevel88: TBevel;
    Label65: TLabel;
    Bevel90: TBevel;
    Panel22: TPanel;
    Panel24: TPanel;
    Panel26: TPanel;
    Panel28: TPanel;
    Bevel91: TBevel;
    Bevel92: TBevel;
    Bevel94: TBevel;
    Bevel95: TBevel;
    Bevel98: TBevel;
    RadioButton44: TRadioButton;
    RadioButton45: TRadioButton;
    RadioButton46: TRadioButton;
    RadioButton47: TRadioButton;
    RadioButton48: TRadioButton;
    Panel29: TPanel;
    Panel30: TPanel;
    Bevel99: TBevel;
    RadioButton49: TRadioButton;
    Bevel100: TBevel;
    RadioButton50: TRadioButton;
    Bevel109: TBevel;
    RadioButton51: TRadioButton;
    Bevel114: TBevel;
    RadioButton52: TRadioButton;
    Bevel115: TBevel;
    RadioButton53: TRadioButton;
    Bevel117: TBevel;
    RadioButton54: TRadioButton;
    Bevel118: TBevel;
    RadioButton55: TRadioButton;
    Panel31: TPanel;
    Bevel119: TBevel;
    Bevel120: TBevel;
    Bevel121: TBevel;
    RadioButton56: TRadioButton;
    RadioButton57: TRadioButton;
    RadioButton58: TRadioButton;
    Panel32: TPanel;
    Bevel122: TBevel;
    Bevel124: TBevel;
    Bevel125: TBevel;
    RadioButton59: TRadioButton;
    RadioButton60: TRadioButton;
    RadioButton61: TRadioButton;
    Panel35: TPanel;
    Panel39: TPanel;
    Panel44: TPanel;
    Panel45: TPanel;
    Bevel126: TBevel;
    Bevel132: TBevel;
    Bevel133: TBevel;
    RadioButton62: TRadioButton;
    RadioButton63: TRadioButton;
    RadioButton64: TRadioButton;
    Bevel134: TBevel;
    Panel47: TPanel;
    Panel66: TPanel;
    Panel33: TPanel;
    Bevel80: TBevel;
    Bevel81: TBevel;
    RadioButton40: TRadioButton;
    RadioButton41: TRadioButton;
    Panel48: TPanel;
    Bevel136: TBevel;
    Bevel137: TBevel;
    RadioButton65: TRadioButton;
    RadioButton66: TRadioButton;
    Panel49: TPanel;
    Panel67: TPanel;
    Bevel135: TBevel;
    Bevel138: TBevel;
    Bevel139: TBevel;
    Bevel140: TBevel;
    RadioButton67: TRadioButton;
    RadioButton68: TRadioButton;
    RadioButton69: TRadioButton;
    RadioButton70: TRadioButton;
    Panel68: TPanel;
    Panel69: TPanel;
    Bevel141: TBevel;
    Bevel142: TBevel;
    Bevel143: TBevel;
    Bevel144: TBevel;
    RadioButton71: TRadioButton;
    RadioButton72: TRadioButton;
    RadioButton73: TRadioButton;
    RadioButton74: TRadioButton;
    Panel70: TPanel;
    Panel71: TPanel;
    Bevel145: TBevel;
    Bevel146: TBevel;
    RadioButton75: TRadioButton;
    RadioButton76: TRadioButton;
    Panel72: TPanel;
    Bevel147: TBevel;
    Panel37: TPanel;
    Panel50: TPanel;
    Panel38: TPanel;
    Bevel106: TBevel;
    Bevel148: TBevel;
    Bevel149: TBevel;
    Bevel150: TBevel;
    Bevel152: TBevel;
    RadioButton31: TRadioButton;
    RadioButton32: TRadioButton;
    RadioButton77: TRadioButton;
    RadioButton78: TRadioButton;
    RadioButton79: TRadioButton;
    Panel51: TPanel;
    Panel52: TPanel;
    Panel53: TPanel;
    Bevel153: TBevel;
    Bevel158: TBevel;
    Bevel159: TBevel;
    RadioButton80: TRadioButton;
    RadioButton81: TRadioButton;
    RadioButton82: TRadioButton;
    Bevel160: TBevel;
    Panel54: TPanel;
    Panel55: TPanel;
    Panel73: TPanel;
    Bevel151: TBevel;
    Bevel154: TBevel;
    Bevel155: TBevel;
    Bevel156: TBevel;
    RadioButton83: TRadioButton;
    RadioButton84: TRadioButton;
    RadioButton85: TRadioButton;
    RadioButton86: TRadioButton;
    Panel76: TPanel;
    Panel74: TPanel;
    Bevel157: TBevel;
    Bevel161: TBevel;
    Bevel162: TBevel;
    RadioButton87: TRadioButton;
    RadioButton88: TRadioButton;
    RadioButton89: TRadioButton;
    Panel75: TPanel;
    Panel77: TPanel;
    Panel78: TPanel;
    Bevel163: TBevel;
    Bevel164: TBevel;
    Bevel165: TBevel;
    Bevel166: TBevel;
    Bevel167: TBevel;
    RadioButton90: TRadioButton;
    RadioButton91: TRadioButton;
    RadioButton92: TRadioButton;
    RadioButton93: TRadioButton;
    RadioButton94: TRadioButton;
    Panel79: TPanel;
    Bevel168: TBevel;
    Bevel169: TBevel;
    Panel56: TPanel;
    Bevel108: TBevel;
    Label36: TLabel;
    Bevel370: TBevel;
    bbt_Close: TBitBtn;
    stb_Message: TStatusBar;
    Panel57: TPanel;
    ed_PatNm: TEdit;
    pn_PatNo: TPanel;
    pn_Age: TPanel;
    pn_Sex: TPanel;
    Panel20: TPanel;
    Panel58: TPanel;
    Panel59: TPanel;
    DateTimePicker1: TDateTimePicker;
    dtp_item01: TDateTimePicker;
    Panel80: TPanel;
    Edit2: TEdit;
    Bevel36: TBevel;
    Bevel2: TBevel;
    Label129: TLabel;
    Bevel9: TBevel;
    Label5: TLabel;
    Bevel10: TBevel;
    Label6: TLabel;
    Bevel25: TBevel;
    Label10: TLabel;
    Bevel26: TBevel;
    Label12: TLabel;
    Bevel15: TBevel;
    Label7: TLabel;
    Bevel24: TBevel;
    Label9: TLabel;
    Bevel27: TBevel;
    Label13: TLabel;
    Bevel5: TBevel;
    Label14: TLabel;
    Bevel18: TBevel;
    Label15: TLabel;
    Bevel19: TBevel;
    Label16: TLabel;
    Bevel20: TBevel;
    Label17: TLabel;
    Bevel1: TBevel;
    Label1: TLabel;
    Bevel8: TBevel;
    Label4: TLabel;
    Bevel7: TBevel;
    Label11: TLabel;
    Bevel31: TBevel;
    Label18: TLabel;
    Bevel35: TBevel;
    Label19: TLabel;
    Bevel37: TBevel;
    Label20: TLabel;
    Bevel38: TBevel;
    Label21: TLabel;
    Bevel68: TBevel;
    Label25: TLabel;
    Bevel202: TBevel;
    Label52: TLabel;
    Bevel205: TBevel;
    Label53: TLabel;
    Bevel206: TBevel;
    Label54: TLabel;
    Bevel213: TBevel;
    Label55: TLabel;
    Bevel214: TBevel;
    Label56: TLabel;
    Bevel203: TBevel;
    Label57: TLabel;
    Bevel204: TBevel;
    Label58: TLabel;
    Bevel45: TBevel;
    Label22: TLabel;
    Bevel226: TBevel;
    Label61: TLabel;
    Panel7: TPanel;
    Panel25: TPanel;
    Panel8: TPanel;
    Bevel14: TBevel;
    Bevel16: TBevel;
    Bevel17: TBevel;
    Edit10: TEdit;
    RadioButton29: TRadioButton;
    RadioButton30: TRadioButton;
    RadioButton33: TRadioButton;
    Edit1: TEdit;
    Edit3: TEdit;
    Edit4: TEdit;
    Edit5: TEdit;
    Edit6: TEdit;
    Edit7: TEdit;
    Edit8: TEdit;
    Edit9: TEdit;
    Panel2: TPanel;
    Panel3: TPanel;
    Edit11: TEdit;
    DateTimePicker2: TDateTimePicker;
    DateTimePicker3: TDateTimePicker;
    Panel4: TPanel;
    Bevel3: TBevel;
    Bevel4: TBevel;
    Bevel219: TBevel;
    Label60: TLabel;
    Edit12: TEdit;
    RadioButton1: TRadioButton;
    RadioButton2: TRadioButton;
    panel1000: TPanel;
    Bevel11: TBevel;
    Bevel104: TBevel;
    B0003_1: TRadioButton;
    B0003_2: TRadioButton;
    Panel166: TPanel;
    Bevel327: TBevel;
    Bevel13: TBevel;
    Bevel21: TBevel;
    Bevel12: TBevel;
    Bevel22: TBevel;
    Bevel28: TBevel;
    CheckBox199: TCheckBox;
    CheckBox1: TCheckBox;
    CheckBox2: TCheckBox;
    CheckBox3: TCheckBox;
    CheckBox4: TCheckBox;
    CheckBox5: TCheckBox;
    Edit13: TEdit;
    Panel1: TPanel;
    Bevel29: TBevel;
    Bevel30: TBevel;
    Bevel215: TBevel;
    Label59: TLabel;
    Edit14: TEdit;
    RadioButton3: TRadioButton;
    RadioButton4: TRadioButton;
    Panel6: TPanel;
    Bevel33: TBevel;
    Bevel34: TBevel;
    RadioButton5: TRadioButton;
    RadioButton6: TRadioButton;
    Panel15: TPanel;
    Bevel69: TBevel;
    Bevel70: TBevel;
    RadioButton13: TRadioButton;
    RadioButton14: TRadioButton;
    Panel16: TPanel;
    Bevel71: TBevel;
    Bevel72: TBevel;
    Bevel73: TBevel;
    Bevel74: TBevel;
    Bevel75: TBevel;
    Bevel76: TBevel;
    Bevel77: TBevel;
    CheckBox24: TCheckBox;
    CheckBox25: TCheckBox;
    CheckBox26: TCheckBox;
    CheckBox27: TCheckBox;
    CheckBox28: TCheckBox;
    CheckBox29: TCheckBox;
    Edit18: TEdit;
    CheckBox30: TCheckBox;
    Edit24: TEdit;
    Edit25: TEdit;
    Edit26: TEdit;
    Edit27: TEdit;
    Edit28: TEdit;
    Edit29: TEdit;
    B0012_1: TMemo;
    Panel5: TPanel;
    Bevel39: TBevel;
    Bevel40: TBevel;
    RadioButton7: TRadioButton;
    RadioButton8: TRadioButton;
    Panel9: TPanel;
    Bevel41: TBevel;
    Bevel42: TBevel;
    Bevel43: TBevel;
    Bevel44: TBevel;
    Bevel46: TBevel;
    CheckBox6: TCheckBox;
    CheckBox7: TCheckBox;
    CheckBox8: TCheckBox;
    CheckBox9: TCheckBox;
    CheckBox11: TCheckBox;
    Edit15: TEdit;
    Panel10: TPanel;
    Bevel47: TBevel;
    Bevel220: TBevel;
    RadioButton34: TRadioButton;
    RadioButton35: TRadioButton;
    Panel46: TPanel;
    Bevel221: TBevel;
    Bevel222: TBevel;
    Bevel223: TBevel;
    Bevel224: TBevel;
    Bevel225: TBevel;
    CheckBox10: TCheckBox;
    CheckBox109: TCheckBox;
    CheckBox110: TCheckBox;
    CheckBox111: TCheckBox;
    CheckBox112: TCheckBox;
    Edit30: TEdit;
    Panel62: TPanel;
    Bevel227: TBevel;
    Bevel228: TBevel;
    RadioButton36: TRadioButton;
    RadioButton37: TRadioButton;
    Panel64: TPanel;
    Bevel229: TBevel;
    Bevel230: TBevel;
    Bevel231: TBevel;
    Bevel232: TBevel;
    Bevel233: TBevel;
    CheckBox113: TCheckBox;
    CheckBox114: TCheckBox;
    CheckBox115: TCheckBox;
    CheckBox116: TCheckBox;
    CheckBox117: TCheckBox;
    Edit31: TEdit;
    Bevel6: TBevel;
    Bevel23: TBevel;
    procedure bbt_CloseClick(Sender: TObject);
    procedure FormDestroy(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure FormShow(Sender: TObject);
    procedure pc_ICUChange(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  MDN110FM2: TMDN110FM2;

implementation

uses
   CComFunc, VarCom, TuxCom, MsgCom, MDCLASS1, MComFunc, HisUtil;

{$R *.DFM}

procedure TMDN110FM2.bbt_CloseClick(Sender: TObject);
begin
   close;
end;

procedure TMDN110FM2.FormDestroy(Sender: TObject);
begin
   MDN110FM2 := nil;
end;

procedure TMDN110FM2.FormClose(Sender: TObject; var Action: TCloseAction);
begin
   Action := Cafree;
end;

procedure TMDN110FM2.FormShow(Sender: TObject);
begin
   pc_ICU.ActivePageIndex := 0;

   sbox_Tab2.HorzScrollBar.Position := 0;
   sbox_Tab2.VertScrollBar.Position := 0;

end;

procedure TMDN110FM2.pc_ICUChange(Sender: TObject);
begin
   sbox_Tab2.HorzScrollBar.Position := 0;
   sbox_Tab2.VertScrollBar.Position := 0;
end;

initialization
    RegisterClass(TMDN110FM2);

finalization
    UnRegisterClass(TMDN110FM2);

end.
